// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp8y81DXw_7NVAVjDBRJtQqWHHbTNAUXg',
    appId: '1:193303518481:web:65a8f745f3da2ab2f900b0',
    messagingSenderId: '193303518481',
    projectId: 'k20-oto',
    authDomain: 'k20-oto.firebaseapp.com',
    storageBucket: 'k20-oto.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbfy8s5vE9W1ZkHWzpmBgGeKypSNDg82M',
    appId: '1:193303518481:android:f625498ebfb22d70f900b0',
    messagingSenderId: '193303518481',
    projectId: 'k20-oto',
    storageBucket: 'k20-oto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRNIwwAzsVTfalToXjqYhxvpjA-GkT22s',
    appId: '1:193303518481:ios:99e30c966727c913f900b0',
    messagingSenderId: '193303518481',
    projectId: 'k20-oto',
    storageBucket: 'k20-oto.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRNIwwAzsVTfalToXjqYhxvpjA-GkT22s',
    appId: '1:193303518481:ios:a386ac2f03cd08cdf900b0',
    messagingSenderId: '193303518481',
    projectId: 'k20-oto',
    storageBucket: 'k20-oto.appspot.com',
    iosBundleId: 'com.example.mobile.RunnerTests',
  );
}
